function [nml, obsPsdFit, fitresult, gof] = createGammaFit(binMid, obsPSD)
	%CREATEFIT(CIP_BINMID,PSD3)
	%  Create a fit.
	%
	%  Data for 'GammaFit' fit:
	%      X Input : cip_binMid
	%      Y Output: PSD3
	%  Output:
	%      fitresult : a fit object representing the fit.
	%      gof : structure with goodness-of fit info.
	
	%  Auto-generated by MATLAB on 24-Jan-2017 09:48:34
	
	
	%% Fit: 'GammaFit'.
	[xData, yData] = prepareCurveData( binMid, obsPSD );
	
	% Set up fittype and options.
	ft = fittype( 'a*x^b*exp(-c*x)', 'independent', 'x', 'dependent', 'y' );
	opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
	opts.Display = 'Off';
	opts.Robust = 'Bisquare';
	opts.StartPoint = [0.957166948242946 0.485375648722841 0.8002804688888];
	
	% Fit model to data.
	[fitresult, gof] = fit( xData, yData, ft, opts );
	
	nml = coeffvalues(fitresult);
	
	obsPsdFit = f_mygamma(nml,xData);
	
end

function [ obsPsdFit ] = f_mygamma( nml, x )
	% Calculate the continuous psd for the distribution
	%   nml: log10(N0), mu, lambda
	
	%N1=10^nml(1);
	%m1=nml(2);
	%l1=nml(3);
	
	obsPsdFit = nml(1).*(x.^nml(2)).*exp(-nml(3).*x);
	
end
